# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run lint
          - "echo \"export const env = {production: true, backend: 'http://api.glonass.io'};\" >> ./src/env.ts"
          - npm run build
          - ssh "$server" "mkdir -p $destiny" && scp -r "$src" "$server:$destiny/$BITBUCKET_COMMIT" && ssh "$server" "ln -sf $destiny/$BITBUCKET_COMMIT $symlink"
  tags:
      release-*:
        - step:
            script:
            - npm install
            - npm run lint
            - "echo \"export const env = {production: true, backend: 'http://api.glonass.io'};\" >> ./src/env.ts"
            - npm run build
            - ssh "$server" "mkdir -p $destiny" && scp -r "$src" "$server:$destiny/$BITBUCKET_TAG" && ssh "$server" "ln -sf $destiny/$BITBUCKET_TAG $symlink"